version: '3.8'

services:
  app:
    build: .
    ports:
      - '3001:3001' # Exponer el puerto 3001 al host para acceso externo
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run dev
    restart: always  # Reiniciar contenedor en caso de fallo

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - '5432:5432' # Exponer el puerto 5432 al host para acceso externo
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    ports:
      - '6379:6379' # Exponer el puerto 6379 al host para acceso externo

volumes:
  pgdata:
