#!/bin/sh
. "$(dirname "$0")/husky.sh"

echo "Ejecutando pre-commit hook"

# Aquí se pueden agregar otras validaciones, como ejecutar pruebas
# echo "Paso 1: Corriendo pnpm test"
# if ! pnpm test; then
#   echo "Error: Las pruebas han fallado"
#   exit 1
# fi

echo "Pre-commit hook finalizado con éxito"
